<Project Sdk="Aspire.AppHost.Sdk/13.2.4">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>MemQuranDashboard.AppHost</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="13.4.3" />
    <PackageReference Include="Aspire.Hosting.Azure.Functions" Version="13.4.3" />
    <PackageReference Include="Aspire.Hosting.Redis" Version="13.4.3" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\..\..\memquran-dashboard-api\src\MemQuranDashboard.Api\MemQuranDashboard.Api.csproj" />
    <ProjectReference Include="..\..\..\memquran-dashboard-integrations\src\Integrations.Api\Integrations.Api.csproj" />
    <ProjectReference Include="..\..\..\memquran-dashboard-integrations\src\Integrations.Sentry.Functions\Integrations.Sentry.Functions.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <None Update="appsettings.Development.json">
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
  </ItemGroup>

</Project>
